src/main/resources/assets/rtm/lang/ru_RU.lang
actualization translate for KaizPatchX
=> Update ru_RU.lang (actualization translate)

src/main/java/jp/ngt/rtm/entity/npc/NPCAIRideTrain.java, src/main/java/jp/ngt/rtm/entity/train/parts/EntityTie.java
This reverts commit 70b759f0d1f5e9ea6857b0909664636827f0f89b.
(cherry picked from commit e1b3af90174a5ece8bfc1e9e26a71ece83e32646)
ForgeGradle 1.2-1.0.6で修正しました。
https://github.com/anatawa12/ForgeGradle-1.2/actions/runs/794939493
=> Revert "#17 #18 ラムダ式にするとエラー吐くので戻し"

build.gradle, src/main/java/jp/ngt/ngtlib/io/NGTFileLoader.java
=> use jar in jar

src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java
=> fix: mouse button may not work as a key

README.ja.md, README.md
=> fixRTMへのリンクを追加

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/CommonProxy.java, src/main/java/jp/ngt/rtm/event/RTMEventHandler.java, src/main/java/jp/ngt/rtm/modelpack/ModelPackLoadThread.java
=> Crashreport on server

src/main/java/jp/ngt/ngtlib/util/PermissionManager.java, src/main/java/jp/ngt/rtm/RTMCore.java
Closes #52, see https://github.com/fixrtm/fixRTM/blob/ae62f391058893825ea5f7333e8ceb36ba4ef2fc/src/main/ngtlib-patches/jp/ngt/ngtlib/util/PermissionManager.java.pm.patch#L21-L52
=> Port permissions

src/main/java/jp/ngt/rtm/rail/BlockLargeRailBase.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java
=> [Fix] crash by StackOverflow

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/rail/RenderLargeRail.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java
Coreのみで描画しているのをそのRenderTickで最初に呼ばれたBaseでに変更
=> [Improve] Render without railcore loaded

src/main/java/jp/kaiz/kaizpatch/fixrtm/Utils.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/caching/FileCache.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/caching/ModelPackBasedCache.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/caching/TaggedFileManager.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/model/CachedPolygonModel.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/model/CachedPolygonModelFormat.txt, src/main/java/jp/kaiz/kaizpatch/fixrtm/model/ModelLoader.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXFileLoader.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXModelPack.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXResource.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/util/ArrayPool.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/util/DigestUtils.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/util/MultiCloseScope.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/util/SortedFileTreeWalk.kt
Copyright noticeの年号が正しくなかったので修正しました。
=> use copyright notice by upstream

src/main/java/jp/ngt/ngtlib/renderer/model/PolygonModel.java
=> charset detection for PolygonModel

src/main/java/jp/ngt/ngtlib/util/PermissionManager.java
=> port -all permission target

src/main/java/jp/ngt/rtm/command/CommandRTM.java
=> [Fix] Can't execute /rtm delAllTrain from console

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java
revert 0869462ced21e25edea47365d7d1c53e54a5e3d8
=> [Fix] low slung train not moving

src/main/java/jp/ngt/rtm/electric/TileEntitySignal.java
https://github.com/Kai-Z-JP/KaizPatchX/commit/77bf2895081864b38cabd5a9a4ae5caffad55441#r55074671
=> [Fix] Y height of Signal RenderBoundingBox is incorrect

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/rail/RenderLargeRail.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityTurnTableCore.java
=> [Revert] rail rendering is too laggy

src/main/java/jp/ngt/ngtlib/io/ScriptUtil.java
=> [Add] Support for ES6

src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java, src/main/java/jp/ngt/rtm/entity/train/util/TrainSpeedManager.java, src/main/java/jp/ngt/rtm/modelpack/cfg/TrainConfig.java
=> [Add] Variable acceleration/deceleration train

src/main/java/jp/ngt/rtm/RTMEntity.java, src/main/java/jp/ngt/rtm/entity/train/parts/RenderSeat.java, src/main/java/jp/ngt/rtm/entity/vehicle/VehicleTrackerEntry.java
電車の座席が電車が傾いても水平のままである問題を修正
223系など
=> [Fix] train seat does not tilt by train roll

src/main/java/jp/ngt/rtm/rail/RenderMarkerBlock1122.java, src/main/java/jp/ngt/rtm/rail/TileEntityMarker.java, src/main/java/jp/ngt/rtm/rail/util/MarkerState.java
レンチに追加し機能を1.12.2版マーカーにも追加(fixRTMより移植)
=> [Add] Fit neighbor setting to 1.12.2 Marker

src/main/java/jp/ngt/rtm/entity/vehicle/EntityVehicleBase.java
=> [Fix] Crash by NPE when placing ship

src/main/java/jp/ngt/mcte/gui/GuiElementFloat.java, src/main/java/jp/ngt/mcte/gui/GuiElementInt.java, src/main/java/jp/ngt/mcte/gui/GuiElementString.java, src/main/java/jp/ngt/ngtlib/gui/GuiButtonCustom.java, src/main/java/jp/ngt/ngtlib/gui/GuiContainerCustom.java, src/main/java/jp/ngt/ngtlib/gui/GuiScreenCustom.java, src/main/java/jp/ngt/ngtlib/gui/GuiTextFieldCustom.java, src/main/java/jp/ngt/rtm/entity/npc/EntityMotorman.java, src/main/java/jp/ngt/rtm/gui/DataMapEditor.java, src/main/java/jp/ngt/rtm/gui/GuiSelectModel.java, src/main/java/jp/ngt/rtm/item/ItemWithModel.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetBase.java, src/main/java/jp/ngt/rtm/modelpack/state/ResourceState.java
=> [Port] color, name, DataMapEditor from GuiSelectModel in 1.12.2

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/RTMBlock.java, src/main/java/jp/ngt/rtm/block/BlockLinePole.java, src/main/java/jp/ngt/rtm/block/RenderBlockLinePole.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntityOrnament.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntityPole.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntityScaffold.java, src/main/java/jp/ngt/rtm/electric/BlockSignal.java, src/main/java/jp/ngt/rtm/electric/RenderSignal.java, src/main/java/jp/ngt/rtm/electric/RenderSignalBaseBlock.java, src/main/java/jp/ngt/rtm/electric/TileEntitySignal.java, src/main/java/jp/ngt/rtm/gui/DataMapEditor.java, src/main/java/jp/ngt/rtm/item/ItemSignal.java, src/main/java/jp/ngt/rtm/item/ItemWithModel.java, src/main/resources/assets/rtm/lang/en_US.lang, src/main/resources/assets/rtm/lang/ja_JP.lang, src/main/resources/assets/rtm/lang/ru_RU.lang, src/main/resources/assets/rtm/lang/zh_CN.lang, src/main/resources/assets/rtm/lang/zh_TW.lang
TileEntityOrnamentの移植に関するバグの修正
=> Fix a bug related to the porting of TileEntityOrnament

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java, src/main/java/jp/ngt/rtm/rail/BlockLargeRailBase.java
=> [Fix] The train is on the rails is detected by the another rail nearby too

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java
=> [Fix] Crash on NPE when loading a broken train

build.gradle, src/main/java/jp/ngt/rtm/ClientProxy.java
=> [Add] Support webp images

src/main/java/jp/ngt/rtm/electric/TileEntityConnectorBase.java
バージョン1.7.10.34以下の碍子のモデル選択ができないバージョンからのアップデートに対応
[Twitter@OEKKKN4649](https://twitter.com/OEKKKN4649)のワールド提供に感謝
=> [Add] Support legacy(34 or less) connectors

src/main/java/jp/ngt/rtm/RTMCore.java
Ports: fixrtm/fixRTM#305
Co-authored-by: anatawa12 <anatawa12@icloud.com>
=> fix Sounds from Immersive vehicles not working

build.gradle
#174用
META-INF/services/**のファイルが含まれていないのを修正
=> [Update] include META-INF/services/**

src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailBase.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSlopeCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSwitchCore.java
=> [Add] render aabb to rail

src/main/java/jp/ngt/rtm/gui/GuiSelectModel.java
=> Fix gui select model

src/main/java/jp/ngt/rtm/block/tileentity/TileEntityFluorescent.java
=> [Fix] angle of the fluorescent is opposite

build.gradle
=> use maven.minecraftforge.net

src/main/java/jp/ngt/rtm/gui/GuiIngameCustom.java
=> [Fix] Train gui(only text) was not rendered in case of notDisplayCab

src/main/java/jp/ngt/rtm/rail/BlockMarker.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityMarker.java, src/main/java/jp/ngt/rtm/rail/util/RailMap.java, src/main/java/jp/ngt/rtm/rail/util/RailMapBasic.java, src/main/java/jp/ngt/rtm/rail/util/RailMapCustom.java, src/main/java/jp/ngt/rtm/rail/util/RailMapSlope.java, src/main/java/jp/ngt/rtm/rail/util/RailMapSwitch.java, src/main/java/jp/ngt/rtm/rail/util/RailMapTurntable.java
更新されたRailMapを1.12.2より移植(RailMapCustom及び互換性対策)
=> [Port] new railmap from 1.12.2

src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java
addNotchではなくsetNotchでノッチ操作をした場合にブレーキ緩解音が鳴らない問題を修正
=> [Fix] Brake release sound doesn't sound when setNotch

src/main/java/jp/ngt/rtm/block/BlockScaffold.java, src/main/resources/assets/minecraft/scripts/RenderScaffold.js
足場の手すりの描画位置がおかしい問題を修正
closes #219
=> [Fix] Rendering position of scaffolding railings

src/main/java/jp/ngt/rtm/entity/train/util/TrainState.java
=> [Fix] Train signal can't be set to -1

src/main/java/jp/ngt/rtm/item/ItemWithModel.java
モデル選択がサーバー側と同期されない問題を修正(#221での誤削除を元に)
=> [Fix] Client side ModelState selection is not synchronized with server 

src/main/java/jp/ngt/rtm/command/CommandRTM.java
=> [Fix] Tab completion in /rtm didn't show summon

src/main/java/jp/ngt/rtm/RTMCore.java
=> [Improve] Style of code to load config

src/main/java/jp/ngt/ngtlib/io/NGTLog.java
=> [Fix] NPE when clicking marker

src/main/java/jp/ngt/rtm/item/ItemLinePole.java
BlockOrnament統合前の古い架線柱アイテムの削除(非表示化)
=> [Delete] Old line pole item

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/block/BlockOrnamentBase.java, src/main/java/jp/ngt/rtm/item/RenderItemWithModel.java, src/main/java/jp/ngt/rtm/modelpack/cfg/ModelConfig.java, src/main/resources/assets/minecraft/models/json/ModelOrnament_LinePole01.json, src/main/resources/assets/minecraft/models/json/ModelOrnament_LinePole02.json, src/main/resources/assets/minecraft/models/json/ModelOrnament_LinePoleFrame01.json, src/main/resources/assets/minecraft/models/json/ModelOrnament_SignalPole01.json
アイテムのテクスチャを設定可能に
例として架線柱にアイコンテクスチャを設定(古い架線柱のテクスチャを流用)
=> Custom icon texture

src/main/java/jp/ngt/rtm/block/BlockLinePole.java, src/main/java/jp/ngt/rtm/block/BlockMachineBase.java, src/main/java/jp/ngt/rtm/block/BlockOrnamentBase.java, src/main/java/jp/ngt/rtm/block/BlockSignBoard.java, src/main/java/jp/ngt/rtm/block/tileentity/RenderSignBoard.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntitySignBoard.java, src/main/java/jp/ngt/rtm/electric/BlockSignal.java, src/main/java/jp/ngt/rtm/item/ItemInstalledObject.java, src/main/java/jp/ngt/rtm/item/ItemSignal.java, src/main/java/jp/ngt/rtm/item/ItemWithModel.java
信号踏切等をCtrl押下状態でピックした際にオフセットも同時に保存するように改善
看板にオフセット実装
=> Improve offset

src/main/java/jp/ngt/rtm/modelpack/cfg/VehicleBaseConfig.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetVehicleBaseClient.java, src/main/java/jp/ngt/rtm/sound/SoundUpdaterTrain.java
=> [Add] Change ats sound from model config

src/main/java/jp/ngt/rtm/block/tileentity/TileEntityOrnament.java
SMPのクライアント側でワールドロード時に大量のぬるぽが発生する問題を修正
=> [Fix] NPE when load world on SMP client side

src/main/java/jp/ngt/rtm/rail/util/SwitchType.java
RailMapのStateが見た目と異なる問題をY字及びダイヤモンドクロスでのみ修正(WebCTC向け)
=> [Fix] The state of RailMap was different from what it looked like.

src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java, src/main/java/jp/ngt/rtm/entity/train/util/TrainSpeedManager.java
=> [Fix] Train backing up when stopped

src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSlopeCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSwitchCore.java
まだロードされていないレールについてのパケットを送信しようとするとクラッシュする問題を修正
closes #249 #146
=> [Fix] Crash when sending packet of rail that have not yet been loaded to the client

src/main/java/jp/ngt/rtm/block/BlockMachineBase.java, src/main/java/jp/ngt/rtm/block/BlockRailroadSign.java, src/main/java/jp/ngt/rtm/block/BlockSignBoard.java, src/main/java/jp/ngt/rtm/electric/BlockElectricalWiring.java, src/main/java/jp/ngt/rtm/electric/BlockSignal.java
=> fix: use crowbar to open offset config

src/main/java/jp/ngt/rtm/block/tileentity/TileEntityMachineBase.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntityOrnament.java, src/main/java/jp/ngt/rtm/electric/TileEntityConnectorBase.java, src/main/java/jp/ngt/rtm/electric/TileEntitySignal.java, src/main/java/jp/ngt/rtm/entity/EntityInstalledObject.java, src/main/java/jp/ngt/rtm/entity/npc/EntityNPC.java, src/main/java/jp/ngt/rtm/entity/train/parts/EntityCargoWithModel.java, src/main/java/jp/ngt/rtm/entity/vehicle/EntityVehicleBase.java, src/main/java/jp/ngt/rtm/gui/DataMapEditor.java, src/main/java/jp/ngt/rtm/modelpack/cfg/ModelConfig.java, src/main/java/jp/ngt/rtm/modelpack/cfg/ResourceConfig.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetBase.java, src/main/java/jp/ngt/rtm/modelpack/state/DataFormatter.java, src/main/java/jp/ngt/rtm/modelpack/state/DataMap.java
=> [Port] ResourceConfig from 1.12.2

src/main/java/jp/ngt/rtm/command/CommandRTM.java
実行者が運転席乗車中に/rtm delRidingFormationコマンドでその編成を削除する機能を追加
=> feat(commands): Add /rtm delRidingFormation

src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java
=> fix(keys/notch): notch would in/decrement when moment got on train

src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java
マウスホイールで行き先を変更したときにその個数の範囲外になる問題を修正
=> fix(gui/trains): Destination index was overflowed when in/decrement by wheel

src/main/java/jp/ngt/rtm/modelpack/CrashableFutureTask.java, src/main/java/jp/ngt/rtm/modelpack/ModelPackLoadThread.java, src/main/java/jp/ngt/rtm/modelpack/texture/TextureManager.java
=> fix(init/loading-model): exceptions was ignored when loading model

src/main/java/jp/ngt/rtm/entity/train/EntityFreightCar.java, src/main/java/jp/ngt/rtm/entity/train/parts/EntityContainer.java, src/main/java/jp/ngt/rtm/entity/train/parts/EntityVehiclePart.java
=> fix(entity/cargo): NPE when installing container on freight car

src/main/java/jp/ngt/rtm/ClientProxy.java, src/main/java/jp/ngt/rtm/RTMConfig.java, src/main/java/jp/ngt/rtm/RTMCore.java, src/main/java/jp/ngt/rtm/block/tileentity/MirrorObject.java, src/main/java/jp/ngt/rtm/block/tileentity/RenderConverter.java, src/main/java/jp/ngt/rtm/block/tileentity/RenderEffect.java, src/main/java/jp/ngt/rtm/block/tileentity/RenderPipe.java, src/main/java/jp/ngt/rtm/entity/EntityBullet.java, src/main/java/jp/ngt/rtm/entity/train/parts/RenderArtillery.java, src/main/java/jp/ngt/rtm/event/RTMEventHandler.java, src/main/java/jp/ngt/rtm/event/RTMTickHandlerClient.java, src/main/java/jp/ngt/rtm/gui/RTMConfigGuiFactory.java, src/main/java/jp/ngt/rtm/item/ItemGun.java, src/main/java/jp/ngt/rtm/modelpack/ModelPackLoadThread.java, src/main/java/jp/ngt/rtm/modelpack/ModelPackUploadThread.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetContainerClient.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetFirearmClient.java, src/main/java/jp/ngt/rtm/network/PacketNoticeHandlerClient.java, src/main/java/jp/ngt/rtm/rail/BlockMarker.java, src/main/java/jp/ngt/rtm/rail/RenderMarkerBlock.java, src/main/java/jp/ngt/rtm/rail/RenderMarkerBlockBase.java, src/main/java/jp/ngt/rtm/sound/MovingSoundEntity.java, src/main/java/jp/ngt/rtm/sound/MovingSoundTileEntity.java, src/main/java/jp/ngt/rtm/util/DummyRenderer.java
=> feat(gui/config): support config gui

src/main/java/jp/ngt/ngtlib/protection/ProtectionManager.java, src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java, src/main/java/jp/ngt/rtm/entity/vehicle/EntityVehicleBase.java, src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java, src/main/java/jp/ngt/rtm/modelpack/cfg/TrainConfig.java, src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetTrain.java
ATS Soundの実装を改善
guiのデバッグ用文字列を削除
MAX_PANTOGRAPH_MOVEを40に修正
保護されたレールに車両を設置できるように変更
=> Improve train

src/main/java/jp/ngt/mcte/gui/GuiEditor.java, src/main/java/jp/ngt/ngtlib/gui/GuiScreenCustom.java, src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java, src/main/java/jp/ngt/rtm/modelpack/cfg/VehicleBaseConfig.java
Custom Button Tipsを移植
MCTEのEditorでタブキー選択を使用した際に、二つ目のフィールドから始まる問題を修正
=> Improve gui

src/main/java/jp/ngt/rtm/event/RTMEventHandler.java
プレーヤーがログアウトした際に列車を削除せず非常ブレーキを掛ける機能を追加
=> feat(train): don't kill the train that the logged out player was on

src/main/java/jp/ngt/ngtlib/util/PermissionManager.java
closes #297 
- permissionリスト内で同一プレイヤーが重複する問題を修正
- パーミッション要求メッセージを本人のみの要求に変更
=> Fix permission list

src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java
=> feat(key): keys to control pantograph/destination

src/main/java/jp/ngt/rtm/electric/BlockTicketVendor.java
=> feat(gui): support offset in ticket vendor

src/main/java/jp/ngt/rtm/entity/train/parts/EntityVehiclePart.java
ported from RTM1.7.10.42
いわゆる椅子シコ問題解決
=> feat(train): optimize train parts update order

src/main/java/jp/ngt/ngtlib/util/PermissionManager.java
=> fix(permission): crash when loading permissions.txt

src/main/java/jp/ngt/rtm/electric/RenderElectricalWiring.java, src/main/java/jp/ngt/rtm/electric/TileEntityConnectorBase.java, src/main/java/jp/ngt/rtm/electric/TileEntityDummyEW.java, src/main/java/jp/ngt/rtm/electric/TileEntityElectricalWiring.java, src/main/java/jp/ngt/rtm/entity/EntityInstalledObject.java, src/main/java/jp/ngt/rtm/entity/EntityTrainDetector.java, src/main/java/jp/ngt/rtm/entity/RenderEntityInstalledObject.java
=> fix(render/wire): wire connected from entity to entity not rendered

src/main/java/jp/ngt/rtm/rail/BlockMarker.java
RailMap編集権限の確認がクライアント側のため、SMPで編集できるのにもかかわらずエラーメッセージが出る問題を修正
=> fix: side where check permissions to edit RailMap

src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXFileLoader.kt, src/main/java/jp/ngt/ngtlib/io/NGTFileLoader.java
See Also: fixrtm/fixRTM@87e6714f8bab96583b195b77eb2bc0008d625bad
See Also: fixrtm/fixRTM@934abf99af4447b5ffc9b390d132fe828b6e6d5a
This fixes problems on loading models in my dev environment.
=> chore: apply fixRTM upstream changes

src/main/java/jp/kaiz/kaizpatch/gui/GuiButtonWithScrollingListBox.kt, src/main/java/jp/kaiz/kaizpatch/gui/GuiScrollingListBox.kt, src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java
=> feat: drop down menu

src/main/java/jp/ngt/ngtlib/world/NGTWorld.java
ミニチュアモデルロード時にクラッシュする問題を修正
closes #329
=> fix: crash when load miniature model

src/main/java/jp/ngt/rtm/render/RailPartsRenderer.java
=> feat: log model name when a script error occurs

src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXFileLoader.kt
=> fix: model not loaded in dev env

src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java
=> fix: NPE when key pressed

src/main/java/jp/ngt/rtm/entity/npc/EntityMotorman.java, src/main/java/jp/ngt/rtm/entity/npc/EntityNPC.java, src/main/java/jp/ngt/rtm/item/ItemNPC.java
=> feat(npc): store nbt data in picked result item

src/main/java/jp/kaiz/kaizpatch/fixrtm/rtm/rail/util/SwitchType.kt, src/main/java/jp/kaiz/kaizpatch/fixrtm/util/Geometrix.kt, src/main/java/jp/ngt/ngtlib/math/NGTMath.java, src/main/java/jp/ngt/rtm/rail/BlockMarker.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSwitchCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityMarker.java, src/main/java/jp/ngt/rtm/rail/TileEntityTurnTableCore.java, src/main/java/jp/ngt/rtm/rail/util/RailMaker.java, src/main/java/jp/ngt/rtm/rail/util/RailMapBasic.java, src/main/java/jp/ngt/rtm/rail/util/RailMapSlope.java, src/main/java/jp/ngt/rtm/rail/util/RailMapSwitch.java, src/main/java/jp/ngt/rtm/rail/util/RailMapTurntable.java, src/main/java/jp/ngt/rtm/rail/util/SwitchType.java
=> Railmap versioning

src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java
=> feat(key): log ats key pressed

src/main/java/jp/ngt/rtm/electric/RenderElectricalWiring.java, src/main/java/jp/ngt/rtm/electric/TileEntityConnectorBase.java, src/main/java/jp/ngt/rtm/render/WirePartsRenderer.java
=> feat(rendering/wire): support transparent in wires

src/main/java/jp/ngt/rtm/rail/RenderMarkerBlock1122.java, src/main/java/jp/ngt/rtm/rail/RenderMarkerBlock1710.java
=> fix: oscillation of marker line

src/main/java/jp/ngt/rtm/RTMBlock.java, src/main/java/jp/ngt/rtm/item/ItemWrench.java, src/main/java/jp/ngt/rtm/rail/BlockMarker.java, src/main/java/jp/ngt/rtm/rail/RenderMarkerBlock1122.java, src/main/java/jp/ngt/rtm/rail/RenderMarkerBlockBase.java, src/main/java/jp/ngt/rtm/rail/TileEntityMarker.java, src/main/resources/assets/rtm/lang/en_US.lang, src/main/resources/assets/rtm/lang/ja_JP.lang, src/main/resources/assets/rtm/lang/ko_KR.lang, src/main/resources/assets/rtm/lang/ru_RU.lang, src/main/resources/assets/rtm/lang/zh_CN.lang, src/main/resources/assets/rtm/lang/zh_TW.lang
=> feat(rail): straight marker

src/main/java/jp/ngt/rtm/item/ItemSignal.java
- 信号設置時にアイテムのDataMapが反映されない問題を修正
=> fix: DataMap in item was not reflected when placing a signal

src/main/java/jp/ngt/rtm/item/ItemWrench.java, src/main/resources/assets/rtm/lang/en_US.lang, src/main/resources/assets/rtm/lang/ja_JP.lang
=> feat: new wrench mode to revert rail to marker

src/main/java/jp/ngt/rtm/entity/vehicle/EntityVehicle.java
自動車乗車時に反時計回りの回転が発生する問題を修正
fixed #398
=> fix: counterclockwise vibration on vehicle

src/main/java/jp/ngt/rtm/electric/BlockElectricalWiring.java, src/main/java/jp/ngt/rtm/electric/EntityElectricalWiring.java
コネクタ/列車検知器/ATCをクリック時にモデル変更GUIを表示する機能を追加
=> Change connector model 

src/main/java/jp/kaiz/kaizpatch/gui/GuiButtonWithScrollingListBox.kt, src/main/java/jp/ngt/ngtlib/gui/GuiButtonCustom.java, src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java
=> Datamap dropdown

src/main/resources/assets/minecraft/models/json/ModelMachine_ATC_01.json, src/main/resources/assets/minecraft/models/json/ModelMachine_ATC_02.json, src/main/resources/assets/minecraft/models/json/ModelMachine_BumpingPost_Type2.json, src/main/resources/assets/minecraft/models/json/ModelMachine_TrainDetector_01.json
=> fix: default models does not follow rail angle

src/main/java/jp/ngt/rtm/entity/EntityInstalledObject.java
=> fix: render distance of EntityInstalledObject is very short

src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailCore.java, src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSwitchCore.java
レールをコピして敷設する際にクラッシュする問題を修正
fixed #390
=> fix: crash when pasting switch rail

src/main/java/jp/ngt/rtm/block/tileentity/TileEntityFluorescent.java, src/main/java/jp/ngt/rtm/block/tileentity/TileEntityScaffold.java
旧バージョンからのモデル移行時にモデルめいが無くなる問題を修正
=> fix: model name is not set when migrating from old vannila rtm

src/main/java/jp/ngt/rtm/block/BlockScaffold.java, src/main/resources/assets/minecraft/scripts/RenderScaffold.js
=> fix: wrong rendering of scaffold

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java, src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java, src/main/java/jp/ngt/rtm/modelpack/cfg/TrainConfig.java
CpFin/Joint/JointReverbがConfigから変更可能に
=> feat: make CpFin/Joint/JointReverb changeable
