src/main/java/jp/ngt/ngtlib/io/NGTClassUtil.java
src/main/java/jp/ngt/ngtlib/io/NGTFileLoader.java

*nix環境での開発のための修正になります。
macOS 11.4上のMohist#28と複数のモデルパックで起動確認しています。

Support development on unix

---

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java
src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java
src/main/java/jp/ngt/rtm/entity/train/util/Formation.java
src/main/java/jp/ngt/rtm/entity/train/util/FormationManager.java
src/main/java/jp/ngt/rtm/sound/SoundUpdaterTrain.java

クライアント側に編成データに両数等の情報が無いことがある問題を修正
主にワールドロード時など

[Fix] Formation data on client side is different from one on server side

---

src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailBase.java

closes #145 
分岐点と終点との高さが違う場合に双方の高さが足された値になっていた

[Fix] Incorrect the height of the block where branch rails with different elevations

---

src/main/java/jp/kaiz/kaizpatch/fixrtm/modelpack/FIXFileLoader.kt

先に古いバージョンのKotlinが別Modによって読み込まれている場合にanatawa12/preload-newer-kotlinへのリンクを表示してクラッシュする機能を追加

[Add] link to anatawa12/preload-newer-kotlin

---

src/main/java/jp/ngt/ngtlib/io/NGTFileLoader.java

モデルロードが終わらない問題が発生するときにinputStreamがnullであることが多かったので

常にFIXFileLoader#getInputStreamを使用するように変更

---

src/main/java/jp/ngt/rtm/item/ItemWithModel.java

```
java.lang.NullPointerException: Unexpected error
at jp.ngt.rtm.item.ItemWithModel.getModelState(ItemWithModel.java:122)
at jp.ngt.rtm.item.ItemWithModel.getResourceState(ItemWithModel.java:117)
at jp.ngt.rtm.gui.GuiSelectModel.func_73866_w_(GuiSelectModel.java:79)
at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:472)
at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:303)
at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:94)
at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
at …
```

[Fix] crash when click ItemWithModel

---

src/main/java/jp/ngt/rtm/rail/BlockMarker.java
src/main/java/jp/ngt/rtm/rail/util/RailMaker.java

分岐タイプが見つからない際のログをサーバー全体からプレイヤー限定で送信するように改善

[Improve] Send logs of switch type error to players only

---

src/main/java/jp/ngt/rtm/electric/TileEntityConnectorBase.java

closes #211 
WirePosの座標移動処理の順番を間違えていたため修正。

[Fix] Misaligned WirePos

---

src/main/java/jp/ngt/ngtlib/math/NGTMath.java
src/main/java/jp/ngt/rtm/command/CommandMCtrl.java
src/main/java/jp/ngt/rtm/command/ModelCtrl.java
src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java

MCtrlのタブ補完が機能していない問題を修正。
MCtrlの引数に範囲外の値を入力した際にクラッシュし、ワールドを読み込めなくなる問題を修正。
closes #217

Fix crash of mctrl

---

src/main/java/jp/ngt/rtm/block/BlockLinePole.java
src/main/java/jp/ngt/rtm/electric/BlockElectricalWiring.java
src/main/java/jp/ngt/rtm/item/ItemInstalledObject.java
src/main/java/jp/ngt/rtm/item/ItemWithModel.java

架線柱/碍子/入出力コネクタのオフセット情報を左Ctrlキー押下状態でスポイトした場合にアイテムへ保存する機能の追加(closes #218)
ResourceStateが存在するアイテム内にDataMapやOffsetが保存されているかをToolTipに表示する機能の追加(As in **(+NBT)**)

Pick offset

---

src/main/java/jp/ngt/rtm/gui/GuiTrainControlPanel.java

カスタムボタンの値が範囲外の時に列車Guiを開くとクラッシュする問題を修正(closes #185)
列車Gui内のボタンの上にカーソルを置き、ホイールを回すことで値を増減させる機能を追加
カスタムボタンの上にカーソルを置き、Fキーを押すことでカスタムボタンの値を全車に反映する機能を追加(closes #215)

Train panel

---

src/main/java/jp/ngt/rtm/block/BlockOrnamentBase.java

closes #228 
port from fixrtm/fixRTM#416
BlockOrnamentBase継承ブロックのオフセット変更用アイテムをItemInstalledObjectからItemCrowbarに変更

[Port/Improve] Change offset item to CrowBar

---

src/main/java/jp/ngt/rtm/modelpack/modelset/ModelSetVehicleBaseClient.java

ダミーモデル(マルチプレイ時にそのモデルがクライアント側に入っていない場合)のATS音声を再生しようとするとクラッシュする問題を修正

[Fix] NPE when playing ats sound of dummy model

---

src/main/java/jp/ngt/rtm/render/ActionParts.java
src/main/java/jp/ngt/rtm/render/PartsRenderer.java

closes #256 
ActionPartsの実装を1.12.2から移植し、どのEntityTrainBaseがクリックされたかを考慮するように修正

[Fix/Port] ActionParts implementation from 1.12.2

---

src/main/java/jp/ngt/rtm/entity/train/util/Formation.java

列車を連結後に運転台から降車せず逆転ハンドルを前または後にして走行すると、列車が重なることがある問題を修正

fix(entity/trains): train overlapped when moved after connecting other train and changing direction

---

src/main/java/jp/ngt/rtm/entity/train/parts/EntityArtillery.java
src/main/java/jp/ngt/rtm/entity/train/parts/EntityCargo.java
src/main/java/jp/ngt/rtm/entity/train/parts/EntityCargoWithModel.java
src/main/java/jp/ngt/rtm/entity/train/parts/EntityContainer.java
src/main/java/jp/ngt/rtm/item/ItemCargo.java
src/main/java/jp/ngt/rtm/item/ItemWithModel.java

コンテナの上にコンテナを設置するとデフォルトモデルになる問題を修正(closes #294)
コンテナを破壊したときにドロップするコンテナアイテムがスタックされない問題を修正
コンテナとコンテナの間にコンテナが置けない問題を修正
クリエイティブモード時にコンテナを破壊したときにコンテナ自身がアイテムとしてドロップする問題を修正
コンテナでもマウスピッキングした際にアイテムを取得する機能を追加

Improve container

---

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java

スニーク時に台車へのクリックを車両へ伝搬し、モデル選択のGUIを開く機能を追加

feat(bogie): open gui of to select train model when click bogie

---

src/main/java/jp/ngt/rtm/ClientProxy.java
src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java
src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java
src/main/java/jp/ngt/rtm/event/RTMKeyHandlerServer.java
src/main/java/jp/ngt/rtm/sound/SoundPlayer.java
src/main/java/jp/ngt/rtm/sound/SoundUpdaterVehicle.java

- Volumeを1以上にしたときに可聴範囲が拡張されない問題を修正
- 踏切音可聴範囲を64ブロックに設定
- 警笛可聴距離を96ブロックに設定
- ブレーキ緩解音可聴範囲を32ブロックに設定
- 台車ジョイント音可聴範囲を64ブロックに設定

Extend audible range

---

.github/ISSUE_TEMPLATE/feature-request-en.yml
.github/ISSUE_TEMPLATE/feature-request-ja.yml

#298 でblankを案内していたので、それよりわかりやすいと思い引っ張ってきました。
KaizPatchXの標準的なライセンスヘッダがわからなかったためKaizPatchX用のライセンスヘッダを挿入していません。提示されたらOpenJDKのASMのような形で両方の併記をしようと思います。

add template for feature request

---

src/main/java/jp/ngt/rtm/sound/SoundUpdaterVehicle.java

closes #335 
最初の音量が0で再生を開始した場合、その後音量を上げても聞こえない問題を修正

fix(sound): if initial volume is 0, can't listen it even if increase volume after that

---

.github/workflows/workflow.yml

chore(ci): disable test due to AWS S3 mirror of Minecraft down

---

src/main/java/jp/ngt/rtm/ClientProxy.java
src/main/java/jp/ngt/rtm/CommonProxy.java
src/main/java/jp/ngt/rtm/RTMConfig.java
src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java
src/main/java/jp/ngt/rtm/entity/train/EntityTrainBase.java
src/main/java/jp/ngt/rtm/event/RTMKeyHandlerServer.java
src/main/java/jp/ngt/rtm/network/PacketPlaySound.java
src/main/java/jp/ngt/rtm/sound/MovingSoundCustom.java
src/main/java/jp/ngt/rtm/sound/MovingSoundEntity.java
src/main/java/jp/ngt/rtm/sound/MovingSoundTileEntity.java
src/main/java/jp/ngt/rtm/sound/MovingSoundTrain.java
src/main/java/jp/ngt/rtm/sound/MovingSoundVehicle.java
src/main/java/jp/ngt/rtm/sound/SoundPlayer.java
src/main/java/jp/ngt/rtm/sound/SoundUpdaterVehicle.java

closes #345
#311の実装の修正
Configから設定可能に
走行音のデフォルトでの可聴範囲を48ブロックに拡張
踏切音のデフォルトでの可聴範囲を32ブロックに変更
台車ジョイント音のデフォルトでの可聴範囲を48ブロックに変更

fix audible range

---

src/main/java/jp/kaiz/kaizpatch/gui/GuiButtonWithScrollingListBox.kt

列車データが範囲外の値の時に列車のGUIを開くとクラッシュする問題を修正

fix(gui): crash when train state data is out of range

---

src/main/java/jp/ngt/mcte/MCTE.java
src/main/java/jp/ngt/mcte/editor/EditorManager.java
src/main/java/jp/ngt/mcte/editor/EntityEditor.java

closes #343 
SMPで再ログイン時にエディターが使えなくなる問題を修正

fix(mcte/editor) editor is unusable when re-join SMP server

---

build.gradle

I've released ForgeGradle 1.2-1.1.x which includes Gradle 8.x support.

chore: use ForgeGradle 1.2-1.1.x

---

src/main/java/jp/ngt/rtm/item/ItemRail.java

斜めに設置されたレールをコピーすると向きがおかしくなる問題を修正

fix(rail): copying diagonally placed rails would result in incorrect orientation

---

src/main/java/jp/ngt/rtm/entity/train/EntityBogie.java

closes #248 
レールの分割精度を修正
port from Kotatsu-RTM/fixRTM#24

fix: rail split accuracy

---

src/main/java/jp/ngt/rtm/RTMBlock.java
src/main/java/jp/ngt/rtm/rail/BlockMarker.java
src/main/resources/assets/rtm/lang/en_US.lang
src/main/resources/assets/rtm/lang/ja_JP.lang

feat: add marker void(non-functional)

---

src/main/java/jp/ngt/rtm/gui/GuiButtonSelectTexture.java
src/main/java/jp/ngt/rtm/gui/GuiSelectTexture.java
src/main/java/jp/ngt/rtm/modelpack/texture/TextureProperty.java

With the old Railroad Sign GUI, it was hard to tell which image was which when there were many similarly shaped images.
We've improved it to display the texutre name as shown in the image below.

Add texture name on railroad sign gui
